export const START_FETCHING_PROJECT = 'features/Project/START_FETCHING_PROJECT'
export const ERROR_FETCHING_PROJECT = 'features/Project/ERROR_FETCHING_PROJECT'
export const SUCCESS_FETCHING_PROJECT = 'features/Project/SUCCESS_FETCHING_PROJECT'